#pragma once

#include "TransformSystem.h"
#include "SpotLightSystem.h"
#include "PointLightSystem.h"
#include "MaterialSystem.h"
#include "InstanceSystem.h"
#include "FrustumCullingSystem.h"
#include "DirlightSystem.h"
#include "DefaultColliderSystem.h"
#include "ScriptSystem.h"
#include "AnimationSystem.h"
#include "TagSystem.h"
#include "ModelSystem.h"
#include "ShapeSystem.h"
#include "AudioSystem.h"
#include "WaterSystem.h"