#pragma once

#include "TransformSystem.h"
#include "SpotLightSystem.h"
#include "PointLightSystem.h"
#include "MaterialSystem.h"
#include "InstanceSystem.h"
#include "FrustumCullingSystem.h"
#include "DirlightSystem.h"
#include "ScriptSystem.h"
#include "AnimationSystem.h"
#include "TagSystem.h"
#include "ModelSystem.h"
#include "ShapeSystem.h"
#include "AudioSystem.h"
#include "WaterSystem.h"

#include "Physics/PhysicsSystem.h"
#include "Physics/DefaultColliderSystem.h"
#include "Physics/BoxColliderSystem.h"
#include "Physics/SphereColliderSystem.h"
#include "Physics/ConvexColliderSystem.h"
#include "Physics/MeshColliderSystem.h"
#include "Physics/RigidbodyDynamicSystem.h"
#include "Physics/RigidbodyStaticSystem.h"